export const CLINIC_LOGIN_REQUEST = 'CLINIC_LOGIN_REQUEST'
export const CLINIC_LOGIN_SUCCESS = 'CLINIC_LOGIN_SUCCESS'
export const CLINIC_LOGIN_FAIL = 'CLINIC_LOGIN_FAIL'
export const CLINIC_LOGOUT = 'CLINIC_LOGOUT'
